### ISSUE TITLE
Xdebug doesn't work on Mac

### ISSUE THREAD

**Issue by dravenk** [INsReady/docker-drupal-dev#1]

**Comment by DravenK** [comment]
由于大部分电脑在连接上网络后都是获取动态 IP 地址，所以首先将网卡 IP 设置为静态 IP，通过
sudo ifconfig en0 alias 10.254.254.254 255.255.255.0
将en0的 IP 设置静态的 IP 别名
通过 ifconfig查看网卡 IP，
找到en0: ，发现类似如下内容
inet 10.254.254.254 netmask 0xff000000 broadcast 255.255.255.0
然后编辑xdebug.ini
vim /vim /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
没有vim的话，可以使用 nano，修改为成如下内容：

zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so  
xdebug.remote_enable=true  
xdebug.remote_host=10.254.254.254  
memory_limit = 1024M

接下来，我们需要配置 PHPstorm ：
在Prefences，或者按【command+,】；
选择：
Languages&Frameworks>PHP>Serves

按你项目访问方式填写Host、Port；
Debugger选择 Xdebug；
勾选 Use path mappings（select if the server is remote or symlinks are used)；
在 Fiele/Directory 选择你的项目路径；
在 Absolute path on the server 选择映射到 docker container 的内部路径；

**Comment by skyred** [comment]
Above suggestion can be as simple as:

If you are using Mac, here is additional step you need to do to make Xdebug working

1. Updating Xdebug configuration inside the container `/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini`

```
xdebug.remote_host=10.254.254.254
xdebug.remote_connect_back=false
```

2. Restart the `drupal-dev` container instance.

To see full explanation, why we is this step necessary, please reed https://gist.github.com/ralphschindler/535dc5916ccbd06f53c1b0ee5a868c93

**Comment by skyred** [comment]
What we can do better is,

1. Add `xdebug.remote_host=10.254.254.254` to `/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini` as default

2. Use a Docker ENV variable to control 'xdebug.remote_connect_back=$VARIABLE' flag when `docker run`

**Comment by DravenK** [comment]
Updating Xdebug configuration inside the container `/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini`
```
zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20160303/xdebug.so  
xdebug.remote_enable=true  
xdebug.remote_host=10.254.254.254    
memory_limit = 1024M 
```

**Comment by skyred** [comment]
> xdebug.remote_enable=true

was already included in the original config. Now, with the latest 8.2 and 8.3 versions, for Mac users, all need to do to make xdebug work is to 

1. Go into the container and change from `xdebug.remote_connect_back=true` to `xdebug.remote_connect_back=false`
2. Restart the container

**Comment by xieyanxy9** [comment]
@DravenK  works for me。

**Comment by xieyanxy9** [comment]
@skyred   it does't need that , @DravenK  ‘s first reply is very useful and complete

**Comment by skyred** [comment]
> @skyred it does't need that

What is not needed? 



> @DravenK ‘s first reply is very useful and complete

No. If you followed his first reply. Then, there is easier way to get Xdebug support on Mac.
