### ISSUE TITLE
drupal console not installed?

### ISSUE THREAD

**Issue by laurencefass** [INsReady/docker-drupal-dev#4]
i've installed and bashed into this for the first time drupal console not installed and im getting an error about a database.

from host:
`# docker run --rm -it --name drupaldev insready/drupal-dev bash
`

once inside container:
`# drush --version`
```
Drush Launcher Version: 0.6.0
Drush Launcher Version: 0.6.0
Drush Commandline Tool 9.2.3
```

`# drupal --version`
```
 [ERROR] Drupal Console is not installed at: "
         /var/www/html"
 You must execute the following composer commands:
 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
```

(i install drupal console)

`# drupal --version`
```
Drupal Console version 1.8.0
 [ERROR] The specified database connection is not defined: default
```

thanks

**Comment by skyred** [comment]
This issue is outdated. Drupal Console was also removed.
